vm_name        = "Image-Registry"
memory         = 4096
vm_id          = 123
cores          = 2
disk_size      = 30
template_name  = "ubuntu"
network_bridge = "vmbr2"
tags           = ["terraform", "ubuntu", "production", "ia"]
vm_user        = "user"
