vm_name        = "Image-Registry"
memory         = 4096
vm_id          = 123
network_bridge = "vmbr1"
ipv4_address   = "10.13.10.123/24"
ipv4_gateway   = "10.13.10.1"
cores          = 2
disk_size      = 30
template_name  = "ubuntu"
tags           = ["terraform", "ubuntu", "production", "ia"]
vm_user        = "user"
