vm_name        = "LiteLLM"
memory         = 8192
vm_id          = 121
cores          = 4
disk_size      = 30
template_name  = "ubuntu"
network_bridge = "vmbr2"
tags           = ["terraform", "ubuntu", "production", "ia"]
vm_user        = "user"
