vm_name       = "Datasyn-Agent"
memory        = 6144
vm_id         = 118
cores         = 4
disk_size     = 30
template_name = "ubuntu"
network_bridge = "vmbr2"
tags          = ["terraform", "ubuntu", "production", "ia"]
vm_user       = "user"
