vm_name        = "Datasyn-DuckDB"
memory         = 6144
vm_id          = 119
cores          = 4
disk_size      = 75
template_name  = "ubuntu"
network_bridge = "vmbr2"
tags           = ["terraform", "ubuntu", "production", "ia"]
vm_user        = "user"
